from bio_embeddings.extract.basic.BasicAnnotationExtractor import BasicAnnotationExtractor, \
    BasicSecondaryStructureResult, BasicExtractedAnnotations, SubcellularLocalizationAndMembraneBoundness
